# Generated by Django 5.1.4 on 2024-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_saved_by_recipe_saved_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.FloatField()),
                ("units", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="blog.ingredient"),
        ),
    ]
