# Generated by Django 5.1.4 on 2024-12-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_ingredient_recipe_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="units",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
