# Generated by Django 5.1.4 on 2024-12-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_ingredient_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="units",
            field=models.CharField(
                blank=True,
                choices=[
                    ("g", "grams"),
                    ("kg", "kilograms"),
                    ("ml", "milliliters"),
                    ("l", "liters"),
                    ("tsp", "teaspoon"),
                    ("tbsp", "tablespoon"),
                    ("cup", "cup"),
                    ("oz", "ounces"),
                    ("lb", "pounds"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
