# Generated by Django 5.1.4 on 2024-12-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_ingredient_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="saved_by",
        ),
    ]
