# Generated by Django 5.1.4 on 2025-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
