# Generated by Django 5.1.4 on 2025-01-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_recipe_image_instruction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.ManyToManyField(
                related_name="recipe_instructions", to="blog.instruction"
            ),
        ),
    ]
