# Generated by Django 5.1.4 on 2025-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_comment_last_edited_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("lactose", "Lactose"),
                            ("gluten", "Gluten"),
                            ("nut", "Nut"),
                            ("meat", "Meat"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="allergens",
            field=models.ManyToManyField(blank=True, to="blog.allergen"),
        ),
    ]
