# Generated by Django 5.1.4 on 2025-01-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_allergen_recipe_allergens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="allergens",
        ),
        migrations.DeleteModel(
            name="Allergen",
        ),
    ]
