# Generated by Django 5.1.4 on 2025-01-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_blogpost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.blogpost",
            ),
        ),
    ]
