# Generated by Django 5.1.4 on 2025-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_comment_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.ManyToManyField(
                blank=True, related_name="recipe_instructions", to="blog.instruction"
            ),
        ),
    ]
