# Generated by Django 5.1.4 on 2025-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
