# Generated by Django 5.1.4 on 2025-01-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="type_of_meal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("snack", "Snack"),
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("supper", "Supper"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
