# Generated by Django 5.1.4 on 2025-01-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_recipe_type_of_meal"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="food_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pasta", "Pasta"),
                    ("salad", "Salad"),
                    ("soup", "Soup"),
                    ("sandwich", "Sandwich"),
                    ("burger", "Burger"),
                    ("pizza", "Pizza"),
                    ("wrap", "Wrap"),
                    ("sauce", "Sauce"),
                    ("dessert", "Dessert"),
                    ("cake", "Cake"),
                    ("cookie", "Cookie"),
                    ("drink", "Drink"),
                    ("other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
