# Generated by Django 5.1.4 on 2025-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_recipe_food_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="type_of_meal",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="contains_allergen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gluten", "Gluten"),
                    ("dairy", "Dairy"),
                    ("eggs", "Eggs"),
                    ("nuts", "Nuts"),
                    ("soy", "Soy"),
                    ("seafood", "Seafood"),
                    ("meat", "Meat"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
