# Generated by Django 5.1.4 on 2025-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_remove_recipe_type_of_meal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="contains_allergen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gluten", "Gluten"),
                    ("dairy", "Dairy"),
                    ("eggs", "Eggs"),
                    ("nuts", "Nuts"),
                    ("soy", "Soy"),
                    ("seafood", "Seafood"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
